#GuitarSet specific arguements for performing tests
[GUITARSET_PATHS]
 # Path where tracks are stored
track_path = data/
# Path were training data are stored
 # Path were annotations are stored
annos_path = data/annos/
# Path were listoftracksfile is stored
dataset_names_path = .
# specify the subset of guitarset to test on. mix for pickup and mic for microphone recordings
; dataset = mix
dataset = mic

tuning = 40, 45, 50, 55, 59, 64
# number of frets of guitar accounted
no_of_frets = 23
sampling_rate = 44100